### ISSUE TITLE
úkol 2

### ISSUE THREAD

**Issue by EvaKolacek** [EvaKolacek/python-kurz-2022#2]
https://github.com/EvaKolacek/python-kurz-2022/blob/main/ukol-02.py

odevzdávám úkol č.2 

druhou část jsem nedokázala doladit k dokonalosti, ale postup tam nechávám, třeba jsem nebyla úplně mimo :-D (jak se tak znám dělám to úplně složitě a je na to jednoduchý postup :-D)

**Comment by lutydlitatova** [comment]
Ahoj, je to na dobré cestě 🙂 Co se týče úkolu, první část je super (vypíšeš všechny státy, které leží v regionu). Druhá část, aby program vypsal "Neznámý region", pokud region nenajde, ještě chce dotáhnout, mně to teď vypíše `False`:

```
Zadej jaký region tě zajímá: X
V regionu X se nachází tyto státy:
False
```

Zkus se na hodnotu proměnné `neznamy` podívat až po skončení cyklu a podle toho určit, jestli se jedná o neznámý region, nebo ne:

```py
neznamy = True

for stat in staty:
    ...  # Pokud mame spravny region, upravis i hodnotu promenne neznamy

# A az ted po skonceni cyklu se podivej na hodnotu promenne neznamy. Pokud je stejna jako pred cyklem, co to znamena?
```

Tohle je jen jedno z možných způsobů řešení, takže když bys to řešila jinak, tak to neva 🙂

**Comment by lutydlitatova** [comment]
A co se týče bonusu (ten je nepovinný), tam doporučuji vytvářet si postupně ten slovník počtů obyvatel. Někde totiž musíme ukládat hodnoty pro jednotlivé subregiony. Kdyžtak napovím víc, zkus napřed dotáhnout ten základní úkol 🙂

**Comment by EvaKolacek** [comment]
https://github.com/EvaKolacek/python-kurz-2022/blob/main/ukol-02.py

nahrála jsem verzi 2 už by měla fungovat správně

**Comment by lutydlitatova** [comment]
To vypadá dobře :tada: ! Píšu bod. Issue zatím nechávám otevřené, kdybys ještě pracovala na bonusu.
