### ISSUE TITLE
úkol 3

### ISSUE THREAD

**Issue by EvaKolacek** [EvaKolacek/python-kurz-2022#3]
https://github.com/EvaKolacek/python-kurz-2022/blob/main/ukol-03.py

předávám ke kontrole domácí úkol č. 3

**Comment by lutydlitatova** [comment]
Paráda, díky!

Tip na zjednodušení podmínky ze tří větví na dvě:
```python
# Tady take bacha, pokud chceme dat napovedu typem, tak zde je cislo str, ne int
def delkaCisla(cislo: str):  
    if len(cislo)==9 or len(cislo)==13:
        return True
    else:
        return False
```

Případně (na někoho už je tato varianta moc zhuštěná, ale pro ukázku):
```python
def delkaCisla(cislo: str):  
    return len(cislo)==9 or len(cislo)==13
```
