### ISSUE TITLE
úkol č.4 - v1

### ISSUE THREAD

**Issue by EvaKolacek** [EvaKolacek/python-kurz-2022#4]
https://github.com/EvaKolacek/python-kurz-2022/blob/main/ukol_04.py

Ahoj Lído,

posílám domácí úkol č.4. Jen bych potřebovala nasměrovat, kde dělám chybu, že mi to dovolí půjčit si auto 2x :-(. Moc děkuji.

**Comment by lutydlitatova** [comment]
Ahoj, vypadá to pěkně, jen jedna drobnost: Podle zadání by informaci o tom, jestli je auto volné nebo ne, měla vypisovat `pujc_auto()`:

> Třídě Auto přidej metodu pujc_auto(), která nebude mít (kromě obligátního self) žádný parametr. Funkce zkontroluje, jestli je vozidlo aktuálně volné. Pokud je volné, změní hodnotu atributu, který určuje, zda je vozidlo půjčené, a vrátí text "Potvrzuji zapůjčení vozidla". Pokud je vozidlo již půjčené, vrátí text "Vozidlo není k dispozici".

A co se týče půjčky dvakrát, vyzkoušej to tak, že dáš do programu dvakrát za sebou třeba `peugeot.pujc_auto()`. Nebo zkopíruj řádky 21-30.  Pokud jsi testovala dvakrát spuštěním programu, tak to prošlo pokaždé, protože python po skončení programu vše "zapomene" a při dalším spuštění postupuje zas od začátku. Upřesním tohle i v zadání.

**Comment by EvaKolacek** [comment]
https://github.com/EvaKolacek/python-kurz-2022/blob/main/ukol_04.py

děkuji za nasměrování a posílám druhou verzi tady to už funguje

**Comment by lutydlitatova** [comment]
Paráda 🙂
